source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'DLUpdater_Example' do
    pod 'DLUpdater', :path => '../'
    
    target 'DLUpdater_Tests' do
        inherit! :search_paths
        
        pod 'Quick'
        pod 'Nimble'
#        pod 'FBSnapshotTestCase'
#        pod 'Nimble-Snapshots'
    end
end
