platform :ios, '8.0'

use_frameworks!

target 'DLUpdater_Example' do
    pod 'DLUpdater', :path => '../'
    
    target 'DLUpdater_Tests' do
        inherit! :search_paths
        
        pod 'Quick', '~> 1.0.0'
        pod 'Nimble', '~> 5.1.1'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end
